env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  no-console: warn
  no-duplicate-imports: error
  no-var: error
  eqeqeq: error
  "@typescript-eslint/no-explicit-any": false
